POST localhost:8080/category
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJtZW1iZXJJZCI6IjIiLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzAzNzc2NTc0fQ.XVKP9V_hH3zswIc0tZPnBgMg2cIDcJSyuewjdZOg1vo
Content-Type: application/json

{
  "teamId": 15,
  "categoryName": "categoryName_169509dcb68c",
  "categoryType": "DOCUMENTS",
  "color": "color_e875edadd488"
}
